### ISSUE TITLE
Image validation conflicts with Spree::Sample loading

### ISSUE THREAD

**Issue by fastjames** [geminimvp/solidus_asset_variant_options#1]
https://github.com/geminimvp/solidus_asset_variant_options/blob/a8d73280ad9d0a2e31762c31ed5e418a91c42564/app/models/spree/image_decorator.rb#L7

This validation clashes with the Spree::Sample load methods in solidus core. You get a result that looks like this:

> Load Sample Data? [y/n]: y
> Loaded Payment Methods samples
> Loaded Tax Categories samples
> Loaded Tax Rates samples
> Loaded Shipping Categories samples
> Loaded Shipping Methods samples
> Loaded Products samples
> Loaded Taxonomies samples
> Loaded Taxons samples
> Loaded Option Types samples
> Loaded Option Values samples
> Loaded Product Option Types samples
> Loaded Product Properties samples
> Loaded Variants samples
> Loaded Stock samples
> rake aborted!
> ActiveRecord::RecordInvalid: Validation failed: Variants must have at least one selection
>
> Tasks: TOP => spree_sample:load

I'm not sure whether we want to change the validation or the sample loader but I wanted to mark my place now before I forgot where I was.

**Comment by fastjames** [comment]
@jordanbyron I think we discussed sensible defaults for this situation in the past but I don't remember where we wound up. In my mind, you could to it a couple of ways in the absence of specific variants with which to associate the image:

1. Associate the image with the master variant
2. Associate the image with all variants

Number 2 seems a little more naive but probably safer as then you don't have any conditional logic elsewhere to say "this variant's images plus the master variant's images." I haven't thought about this in awhile so I may have omitted vital information.

cc @bradediger

**Comment by fastjames** [comment]
Looking more closely at the sample load code, it does appear to be trying to tie an image to a variant:
https://github.com/solidusio/solidus/blob/master/sample/db/samples/assets.rb
 I need to do some more testing to see where that's going wrong.

**Comment by jordanbyron** [comment]
Hey @fastjames! 

Right now the UI is defaulting new image uploads to "All" variants:

![screen shot 2017-10-12 at 9 38 08 am](https://user-images.githubusercontent.com/40662/31498858-178529a2-af31-11e7-9c59-b6b78cf4fc53.png)

Under the hood that just equates to the ID of the "master variant". Here is the commit that enabled that: 69be119c4e12cccef4067f99c0da6ad47462b6c6 We might have to move that logic down into the model to fix this problem but I'm open to suggestions. 

As a side note, `solidus_asset_variant_options` is displaying the master variants ID as "All" in the UI, however in practice that doesn't seem to be the case. For example the "Ruby on Rails Baseball Jersey" product has [2 images](https://engine-storefront-staging.herokuapp.com/admin/products/ruby-on-rails-baseball-jersey/images): 1 for "All" variants and 1 for a specific variant. In the product picker the "All" image is only shown for the master variants and all other variants display no image. 

## Variant with no specific image associated with it

Here I'd expect the "All" image to be displayed, but it is not

![screen shot 2017-10-12 at 9 45 05 am](https://user-images.githubusercontent.com/40662/31499604-43e16162-af33-11e7-9d4d-ed53502852c1.png)

## Variant with a specific image associated with it

![screen shot 2017-10-12 at 9 45 09 am](https://user-images.githubusercontent.com/40662/31499605-441c23f6-af33-11e7-892a-ebfd59b26bca.png)

## Master variant displaying the "All" image

![screen shot 2017-10-12 at 9 45 13 am](https://user-images.githubusercontent.com/40662/31499606-4429669c-af33-11e7-87c4-6c17bfbf3dac.png)

Checking `Spree::Variant#images` for one of the variants without an image associated with it returns an empty association, where I'd expect that to return the "All" image. Again this is tangentially related to the issue you are encountering, but since we are talking about setting defaults I thought it might be worth looking into. Especially if "All" in the context of the UI doesn't seem to correlate to actually adding images to all of the product's variants.

Let me know what you think or if you have any more questions.

**Comment by fastjames** [comment]
@jordanbyron that's exactly the info I was looking for. It sounds like we have 2 things to address:

1. Ensure that images are tied to the product's master variant at a minimum. This is likely happening because the sample store data load task isn't going through the UI. I think a before_validation callback here is OK.
2. Ensure that Variant#images includes images from the master variant. This sounds more like a straight-up bug, double so if the variant tied to that one variant-specific image isn't getting the image.

**Comment by fastjames** [comment]
Right now, a variant's images are accessed via a straight HMT association. So as we thought, it's not including the master variant's images. I can see two solutions:

1. As mentioned earlier, associate images designated 'all' with all variants. This is simple to do, but more complex to maintain because more variants could be added later. For that reason I'm inclined to look for another solution.
2. Override the #images call to pull in images from the master variant. While this is more complex on the front end, I think it's better because it encapsulates reality a bit more cleanly. We can add variants and be assured that they will display the 'all variants' images properly.

Finally, I am having trouble coming up with a way to keep the validation on Image that started this issue. I certainly undestand its intent but I can see more cases arising where we may be creating images semi-independently of products. I'm going to continue testing without it for now.

**Comment by jordanbyron** [comment]
> double so if the variant tied to that one variant-specific image isn't getting the image.

To be clear, `Spree::Variant#images` will return any images specifically associated to that variant. Sorry if I was unclear about this.

> So as we thought, it's not including the master variant's images. I can see two solutions ...

I'm partial to option 2 as well. 

> Finally, I am having trouble coming up with a way to keep the validation on Image that started this issue.

It feels like we want a validation that only gets applied when the image is being created via the UI. Depending on how much we'll need to bypass the validation, I wonder if explicitly requiring a `image.save(validate: false)` call is an acceptable solution. Which is to say "I realize images need a variant to be relevant, but I know when I am doing and I want to create one anyway without a variant". Or the flipside, throw a toggle on the model that only gets turned on (and therefore the validation is only run) when an image is being created / updated via the UI. 

```ruby
class Image
  attr_accessor :validate_variant_presence

  validates :variants,
    length: { minimum: 1,
              message: 'must have at least one selection' ,
              if: -> { validate_variant_presence } # pseudo code is :shrug:
    }
end
```

Both feel a little hacky, but they address the problem without losing the validation entirely.

**Comment by fastjames** [comment]
After a few dead ends, my latest idea has been to override the selection arel like so:

```
Spree::Variant.class_eval do
  has_many :variant_images, -> (object) {
    master = object.product.master
    variant_ids = [object.id, master.id].uniq
    unscope(:where).where(variant_id: variant_ids).order(:variant_id, :position)
  }, class_name: '::Spree::VariantImage'
  has_many :variant_image_images, through: :variant_images, source: :image

  alias_method :images, :variant_image_images
  alias_method :images=, :variant_image_images=
```

This appears to fulfill the primary objective, in that I can now get master variant images to a non-master variant. However, it seems to break the spec that guarantees that an Image can only be associated with a Variant once. This happens because if the association is created via

> some_variant.images << some_image

The join object (VariantImage) has a variant_id of nil. 

I have confirmed that the spec passes in master (after commenting out the validation that started the issue).

**Comment by fastjames** [comment]
My inclination towards having the validation off by default is that we wouldn't have to patch as many spots within Solidus itself, since the core app is going to assume everything is fine and (as seen in Sample) create Images that don't start out with Variants.

**Comment by fastjames** [comment]
Pushed https://github.com/geminimvp/solidus_asset_variant_options/pull/2

**Comment by fastjames** [comment]
See referenced PR. I can make the specs work, but if I try to use the syntax

```
some_variant.images << some_image
```
I'm having the same problem mentioned earlier.

**Comment by fastjames** [comment]
OK, I have all specs green now. I had to replace the Product#variant_images chained association with a slightly complex query, and I gave up on using the shovel operator in the specs. Otherwise I think the change looks pretty decent.

**Comment by fastjames** [comment]
@jordanbyron is there a good way to test / spec that this fixes the problem you identified? I think it does but I want to be sure.

**Comment by fastjames** [comment]
After reading a bit more, I wonder if we could take a slightly different approach and introduce a Variant#display_images method? That way `Variant#images` would still be the images associated with the Variant, and `Variant#display_images` would include the images from the master variant. Variant already has a #display_image method that does something similar with falling back to the parent Product's images.

**Comment by fastjames** [comment]
This appears to be related to the behavior I have been researching: https://github.com/rails/rails/issues/25140

**Comment by fastjames** [comment]
I decided to back up and take another shot at this using my display_images idea, and I like how that branch turned out _much_ better than what I did here. I'm probably going to close this one and open a new PR on that branch so please direct your attention there:
https://github.com/geminimvp/solidus_asset_variant_options/tree/add_variant_display_images

**Comment by fastjames** [comment]
Unless anyone has objections, I'm going to merge the changes on https://github.com/geminimvp/solidus_asset_variant_options/pull/3 today.

**Comment by bradediger** [comment]
I'm fine with that approach. FYI, Jordan is out today and returning
tomorrow, so don't expect his reply today. :-)

Brad
